const countries = [
    "Ireland", 
    "Slovakia", 
    "France", 
    "Italy",  
    "Czech Republic", 
    "Poland", 
    "Spain", 
    "Bangladesh", 
    "Pakistan", 
    "Ghana", 
    "Portugal", 
    "Sri Lanka", 
    "Lithuania",       
    "Belarus",         
    "Hungary",         
    "Bulgaria",       
    "Italy",            
    "Portugal",        
    "Slovenia",      
    "Serbia",          
    "San Marino",     
    "Lithuania",      
    "Hungary",         
    "Moldova",         
    "Azerbaijan",      
    "Bulgaria",         
    "Malta",           
    "Montenegro",      
    "Spain",           
    "Bosnia and Herzegovina", 
    "Kosovo",           
    "North Macedonia"
];
